image: node:latest

cache:
  paths:
    - node_modules/

stages:
  - deploy

before_script:
  - npm install

pages:
 stage: deploy
 script:
  - npm install
  - npm run build
  - rm -rf public
  - mkdir public
  - cp -r dist/* public
 artifacts:
  expire_in: 1 week
  paths:
  - public
 only:
  - master